import { IEssence } from './essence-model';

export interface IWeapon extends IEssence {
  name: string;
  star: number;
}

export const weapons: IWeapon[] = [
  {
    name: 'Artzy Tyrannical',
    star: 6,
    primary: 'int',
    secondary: 'critical rate boost',
    skill: 'fracture',
  },
  {
    name: "Brigand's Calling",
    star: 6,
    primary: 'agi',
    secondary: 'attack boost',
    skill: 'detonate',
  },
  {
    name: 'Chivalric Virtues',
    star: 6,
    primary: 'will',
    secondary: 'hp boost',
    skill: 'medicant',
  },
  {
    name: 'Clannibal',
    star: 6,
    primary: 'main',
    secondary: 'arts intensity boost',
    skill: 'infliction',
  },
  {
    name: 'Delivery Guaranteed',
    star: 6,
    primary: 'will',
    secondary: 'ultimate gain boost',
    skill: 'pursuit',
  },
  {
    name: 'Detonation Unit',
    star: 6,
    primary: 'main',
    secondary: 'arts intensity boost',
    skill: 'detonate',
  },
  {
    name: 'Dreams of Starry Beach',
    star: 6,
    primary: 'int',
    secondary: 'treatment efficiency boost',
    skill: 'infliction',
  },
  {
    name: 'Eminent Repute',
    star: 6,
    primary: 'main',
    secondary: 'physical dmg boost',
    skill: 'brutality',
  },
  {
    name: 'Etch Figure',
    star: 6,
    primary: 'will',
    secondary: 'nature dmg boost',
    skill: 'suppression',
  },
  {
    name: 'Exemplar',
    star: 6,
    primary: 'main',
    secondary: 'attack boost',
    skill: 'suppression',
  },
  {
    name: 'Forgeborn Scathe',
    star: 6,
    primary: 'int',
    secondary: 'attack boost',
    skill: 'twilight',
  },
  {
    name: 'Former Finery',
    star: 6,
    primary: 'will',
    secondary: 'hp boost',
    skill: 'efficacy',
  },
  {
    name: 'Glorious Memory',
    star: 6,
    primary: 'agi',
    secondary: 'critical rate boost',
    skill: 'twilight',
  },
  {
    name: 'Grand Vision',
    star: 6,
    primary: 'agi',
    secondary: 'attack boost',
    skill: 'infliction',
  },
  {
    name: 'Home Longing',
    star: 6,
    primary: 'main',
    secondary: 'attack boost',
    skill: 'assault',
  },
  {
    name: 'JET',
    star: 6,
    primary: 'main',
    secondary: 'attack boost',
    skill: 'suppression',
  },
  {
    name: 'Khravengger',
    star: 6,
    primary: 'str',
    secondary: 'attack boost',
    skill: 'detonate',
  },
  {
    name: 'Lone Barge',
    star: 6,
    primary: 'will',
    secondary: 'attack boost',
    skill: 'suppression',
  },
  {
    name: 'Lupine Scarlet',
    star: 6,
    primary: 'agi',
    secondary: 'critical rate boost',
    skill: 'fracture',
  },
  {
    name: 'Mountain Bearer',
    star: 6,
    primary: 'agi',
    secondary: 'physical dmg boost',
    skill: 'efficacy',
  },
  {
    name: 'Navigator',
    star: 6,
    primary: 'int',
    secondary: 'cryo dmg boost',
    skill: 'infliction',
  },
  {
    name: 'Never Rest',
    star: 6,
    primary: 'will',
    secondary: 'attack boost',
    skill: 'flow',
  },
  {
    name: 'Oblivion',
    star: 6,
    primary: 'int',
    secondary: 'arts dmg boost',
    skill: 'twilight',
  },
  {
    name: 'Rapid Ascent',
    star: 6,
    primary: 'main',
    secondary: 'critical rate boost',
    skill: 'twilight',
  },
  {
    name: 'Sundered Prince',
    star: 6,
    primary: 'str',
    secondary: 'critical rate boost',
    skill: 'crusher',
  },
  {
    name: 'Thermite Cutter',
    star: 6,
    primary: 'will',
    secondary: 'attack boost',
    skill: 'flow',
  },
  {
    name: 'Thunderberge',
    star: 6,
    primary: 'str',
    secondary: 'hp boost',
    skill: 'medicant',
  },
  {
    name: 'Umbral Torch',
    star: 6,
    primary: 'int',
    secondary: 'heat dmg boost',
    skill: 'infliction',
  },
  {
    name: 'Valiant',
    star: 6,
    primary: 'agi',
    secondary: 'physical dmg boost',
    skill: 'combative',
  },
  {
    name: 'Wedge',
    star: 6,
    primary: 'main',
    secondary: 'critical rate boost',
    skill: 'infliction',
  },
  {
    name: 'White Night Nova',
    star: 6,
    primary: 'main',
    secondary: 'arts intensity boost',
    skill: 'infliction',
  },
];
