import { IEssence } from './essence-model';

export interface IWeapon extends IEssence {
  name: string;
  star: number;
}

export const weapons: IWeapon[] = [
  {
    name: 'Artzy Tyrannical',
    star: 6,
    primary: 'int',
    secondary: 'critical rate boost',
    skill: 'fracture',
  },
  {
    name: "Brigand's Calling",
    star: 6,
    primary: 'agi',
    secondary: 'attack boost',
    skill: 'detonate',
  },
  {
    name: 'Chivalric Virtues',
    star: 6,
    primary: 'will',
    secondary: 'hp boost',
    skill: 'medicant',
  },
  {
    name: 'Clannibal',
    star: 6,
    primary: 'main',
    secondary: 'arts intensity boost',
    skill: 'infliction',
  },
  {
    name: 'Delivery Guaranteed',
    star: 6,
    primary: 'will',
    secondary: 'ultimate gain boost',
    skill: 'pursuit',
  },
  {
    name: 'Detonation Unit',
    star: 6,
    primary: 'main',
    secondary: 'arts intensity boost',
    skill: 'detonate',
  },
  {
    name: 'Dreams of Starry Beach',
    star: 6,
    primary: 'int',
    secondary: 'treatment efficiency boost',
    skill: 'infliction',
  },
  {
    name: 'Eminent Repute',
    star: 6,
    primary: 'main',
    secondary: 'physical dmg boost',
    skill: 'brutality',
  },
  {
    name: 'Etch Figure',
    star: 6,
    primary: 'will',
    secondary: 'nature dmg boost',
    skill: 'suppression',
  },
  {
    name: 'Exemplar',
    star: 6,
    primary: 'main',
    secondary: 'attack boost',
    skill: 'suppression',
  },
  {
    name: 'Forgeborn Scathe',
    star: 6,
    primary: 'int',
    secondary: 'attack boost',
    skill: 'twilight',
  },
  {
    name: 'Former Finery',
    star: 6,
    primary: 'will',
    secondary: 'hp boost',
    skill: 'efficacy',
  },
  {
    name: 'Glorious Memory',
    star: 6,
    primary: 'agi',
    secondary: 'critical rate boost',
    skill: 'twilight',
  },
  {
    name: 'Grand Vision',
    star: 6,
    primary: 'agi',
    secondary: 'attack boost',
    skill: 'infliction',
  },
  {
    name: 'Home Longing',
    star: 6,
    primary: 'main',
    secondary: 'attack boost',
    skill: 'assault',
  },
  {
    name: 'JET',
    star: 6,
    primary: 'main',
    secondary: 'attack boost',
    skill: 'suppression',
  },
  {
    name: 'Khravengger',
    star: 6,
    primary: 'str',
    secondary: 'attack boost',
    skill: 'detonate',
  },
  {
    name: 'Lone Barge',
    star: 6,
    primary: 'will',
    secondary: 'attack boost',
    skill: 'suppression',
  },
  {
    name: 'Lupine Scarlet',
    star: 6,
    primary: 'agi',
    secondary: 'critical rate boost',
    skill: 'fracture',
  },
  {
    name: 'Mountain Bearer',
    star: 6,
    primary: 'agi',
    secondary: 'physical dmg boost',
    skill: 'efficacy',
  },
  {
    name: 'Navigator',
    star: 6,
    primary: 'int',
    secondary: 'cryo dmg boost',
    skill: 'infliction',
  },
  {
    name: 'Never Rest',
    star: 6,
    primary: 'will',
    secondary: 'attack boost',
    skill: 'flow',
  },
  {
    name: 'Oblivion',
    star: 6,
    primary: 'int',
    secondary: 'arts dmg boost',
    skill: 'twilight',
  },
  {
    name: 'Rapid Ascent',
    star: 6,
    primary: 'main',
    secondary: 'critical rate boost',
    skill: 'twilight',
  },
  {
    name: 'Sundered Prince',
    star: 6,
    primary: 'str',
    secondary: 'critical rate boost',
    skill: 'crusher',
  },
  {
    name: 'Thermite Cutter',
    star: 6,
    primary: 'will',
    secondary: 'attack boost',
    skill: 'flow',
  },
  {
    name: 'Thunderberge',
    star: 6,
    primary: 'str',
    secondary: 'hp boost',
    skill: 'medicant',
  },
  {
    name: 'Umbral Torch',
    star: 6,
    primary: 'int',
    secondary: 'heat dmg boost',
    skill: 'infliction',
  },
  {
    name: 'Valiant',
    star: 6,
    primary: 'agi',
    secondary: 'physical dmg boost',
    skill: 'combative',
  },
  {
    name: 'Wedge',
    star: 6,
    primary: 'main',
    secondary: 'critical rate boost',
    skill: 'infliction',
  },
  {
    name: 'White Night Nova',
    star: 6,
    primary: 'main',
    secondary: 'arts intensity boost',
    skill: 'infliction',
  },
  {
    name: 'Flickers in the Mist',
    star: 6,
    primary: 'will',
    secondary: 'electric dmg boost',
    skill: 'efficacy',
  },
  {
    name: 'Sundering Steel',
    star: 5,
    primary: 'agi',
    secondary: 'physical dmg boost',
    skill: 'combative',
  },
  {
    name: 'Wild Wanderer',
    star: 5,
    primary: 'int',
    secondary: 'electric dmg boost',
    skill: 'infliction',
  },
  {
    name: 'Fortmaker',
    star: 5,
    primary: 'int',
    secondary: 'ultimate gain boost',
    skill: 'inspiring',
  },
  {
    name: 'Finishing Call',
    star: 5,
    primary: 'str',
    secondary: 'hp boost',
    skill: 'medicant',
  },
  {
    name: 'Chimeric Justice',
    star: 5,
    primary: 'str',
    secondary: 'ultimate gain boost',
    skill: 'brutality',
  },
  {
    name: 'Rational Farewell',
    star: 5,
    primary: 'str',
    secondary: 'heat dmg boost',
    skill: 'pursuit',
  },
  {
    name: 'Monaihe',
    star: 5,
    primary: 'will',
    secondary: 'ultimate gain boost',
    skill: 'inspiring',
  },
  {
    name: 'Stanza of Memorials',
    star: 5,
    primary: 'int',
    secondary: 'attack boost',
    skill: 'twilight',
  },
  {
    name: 'Finchaser 3.0',
    star: 5,
    primary: 'str',
    secondary: 'cryo dmg boost',
    skill: 'suppression',
  },
  {
    name: 'Twelve Questions',
    star: 5,
    primary: 'str',
    secondary: 'cryo dmg boost',
    skill: 'suppression',
  },
  {
    name: 'OBJ Edge of Lightness',
    star: 5,
    primary: 'agi',
    secondary: 'attack boost',
    skill: 'flow',
  },
  {
    name: 'Aspirant',
    star: 5,
    primary: 'agi',
    secondary: 'physical dmg boost',
    skill: 'twilight',
  },
  {
    name: 'Seeker of Dark Lung',
    star: 5,
    primary: 'str',
    secondary: 'ultimate gain boost',
    skill: 'detonate',
  },
  {
    name: 'Ancient Canal',
    star: 5,
    primary: 'str',
    secondary: 'arts intensity boost',
    skill: 'brutality',
  },
  {
    name: 'OBJ Heavy Burden',
    star: 5,
    primary: 'str',
    secondary: 'hp boost',
    skill: 'efficacy',
  },
  {
    name: 'OBJ Razorhorn',
    star: 5,
    primary: 'will',
    secondary: 'physical dmg boost',
    skill: 'infliction',
  },
  {
    name: 'Opus: The Living',
    star: 5,
    primary: 'agi',
    secondary: 'arts dmg boost',
    skill: 'infliction',
  },
  {
    name: 'OBJ Velocitous',
    star: 5,
    primary: 'agi',
    secondary: 'ultimate gain boost',
    skill: 'detonate',
  },
  {
    name: 'Freedom to Proselytize',
    star: 5,
    primary: 'will',
    secondary: 'treatment efficiency boost',
    skill: 'medicant',
  },
  {
    name: 'OBJ Arts Identifier',
    star: 5,
    primary: 'int',
    secondary: 'arts intensity boost',
    skill: 'pursuit',
  },
  {
    name: 'Cohesive Traction',
    star: 5,
    primary: 'will',
    secondary: 'electric dmg boost',
    skill: 'suppression',
  },
];
